import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Designo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>The quick brown fox jumps over the lazy dog</h1>
      <h2>Hello World</h2>
      <h3>Hello World</h3>
      <p>Hello World</p>
      <button className="primary">Click</button>
      <button className="light">Click</button>
    </>
  );
}
